---

- name: Collect SNMP
  gather_facts: true
  hosts: unix_servers
  tasks:

    - name: Install python-pip package
      dnf: name=python3-pip state=latest

    - name: Install pysnmp package
      pip: name=pysnmp state=latest

    - name: Collect SNMP
      snmp_facts:
        host: '{{ inventory_hostname }}'
        version: v2c
        community: public
#      delegate_to: local
